### ISSUE TITLE
Additional Character Logos

### ISSUE THREAD

**Issue by cruth7182** [Kitty-Inu-DAO/Website#29]
The Character Logo section of the Governance Docs section only features Kitty. 
Please include character logo for other characters in the game.
It would be great to see Kit, Bored Ape Cop, Shiba, Pudgy Penguin and any others that could be included.

**Comment by DesiKitty** [comment]
I believe that the DAO has usage rights to the Kitty Inu character logo and Kitty Inu character IP and not to the game characters of KittyKart which are owned by 9VRSE, Inc.

**Comment by cruth7182** [comment]
Okay, makes sense. Thanks!
