### ISSUE TITLE
Need more rick rolls please

### ISSUE THREAD

**Issue by izarex** [Kitty-Inu-DAO/Website#30]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by axtina** [comment]
this was like... so close! 🤣

**Comment by gittigger** [comment]
nooo, pleasssee nooo!

**Comment by Rygel42** [comment]
Closing this before @axtina yield to temptation.
