### ISSUE TITLE
Cloudflare link no worky!

### ISSUE THREAD

**Issue by gittigger** [Kitty-Inu-DAO/Website#32]
**Describe the bug**
URL on README.md not working.

**To Reproduce**
Click on the Cloudflare link

**Expected behavior**
Resolves to the Cloudflare version of the site.

**Actual behaviour**
It fails to resolve.

**Comment by Rygel42** [comment]
Fixed. :)

Thanks for the report!

Please note the site doesn't work correctly on Cloudflare though (and we may not be able to make it works as this Cloudflare service is just unreliable). The .eth.limo URL is preferred, as it just works.

**Comment by Rygel42** [comment]
Closing.
