### ISSUE TITLE
Rickroll speach bubble "holders's" 

### ISSUE THREAD

**Issue by Yellowtangs** [Kitty-Inu-DAO/Website#38]
The word "holders's" should be replaced with: holders'
![Screenshot_20230612_152446_Chrome](https://github.com/Kitty-Inu-DAO/Website/assets/136347942/c511f083-919e-4b15-b7cb-77dddc11e264)

**Comment by Rygel42** [comment]
Fixed by Anna. :)

Will be pushed to prod at a later time.

Thanks for the report!
