### ISSUE TITLE
Social media bar not visible on phone (Brave + Chrome browser) 

### ISSUE THREAD

**Issue by Zaro1988** [Kitty-Inu-DAO/Website#40]
**Describe the bug:**
The social media bar is not fully visible on phone on the main page. Tried with 2 different phones and 2 different browsers.
Even scrolling down does not help to see the social media icons. 

**Screenshots**
![image](https://github.com/Kitty-Inu-DAO/Website/assets/136369518/c7a1432b-922f-4c44-a5a2-f521205899e7)
![image](https://github.com/Kitty-Inu-DAO/Website/assets/136369518/e9a41c3f-5835-4296-a041-08d4995d5590)

**Smartphone (please complete the following information):**
 - Device 1: Xiaomi Redmi 4 X (1st screenshot)
 - Browser 1: Brave

 - Device 2: Xiaomi Redmi Note 10 Lite (2nd screenshot) 
 - Browser 2: Chrome

**Comment by Rygel42** [comment]
Fixed by #48.
