### ISSUE TITLE
Menu bar should be closed comfortably (by touching outside the menu area)

### ISSUE THREAD

**Issue by Zaro1988** [Kitty-Inu-DAO/Website#41]
Intuitively I would expect the menu bar to be closed after touching elsewhere on the screen but it does not. You have to touch the menu button again to close it. 
This would be a convenient feature that everyone expects automatically.

**Screenshots:**
![image](https://github.com/Kitty-Inu-DAO/Website/assets/136369518/73a579a1-a4ab-467d-bd9c-f991a57a485d)

**Smartphone:**

- Device: Xiaomi Redmi 4 X (1st screenshot)

- Browser: Brave

**Comment by axtina** [comment]
addressed in #47
