### ISSUE TITLE
Social icons missing at the bottom of the "About" page

### ISSUE THREAD

**Issue by Zaro1988** [Kitty-Inu-DAO/Website#42]
Tested with 2 different phones 2 different browsers (see details below). It works perfectly in both phones with Chrome but not with Brave browser. 

**Screenshots**
Chrome: 
![image](https://github.com/Kitty-Inu-DAO/Website/assets/136369518/c74f90cd-71bb-42ca-ba26-58b10ba1afc0)

Brave:
![image](https://github.com/Kitty-Inu-DAO/Website/assets/136369518/969b5385-0b61-4fed-bff2-85e37c3c7d16)

Smartphone:

Device 1: Xiaomi Redmi 4 X 

Browser 1: Chrome / Brave

Device 2: Xiaomi Redmi Note 10 Lite

Browser 2: Chrome / Brave

**Comment by axtina** [comment]
addressed in #48 - merged into next release. closing.
