### ISSUE TITLE
Misaligned text on "Tokenomics" page

### ISSUE THREAD

**Issue by Zaro1988** [Kitty-Inu-DAO/Website#44]
The title says it all. On phone with both Chrome and Brave browsers.

**Screenshots**
Brave:
![image](https://github.com/Kitty-Inu-DAO/Website/assets/136369518/9c158dc7-8e26-4622-9a8d-3b1e83626705)

Chrome:
![image](https://github.com/Kitty-Inu-DAO/Website/assets/136369518/6c725019-3878-487f-aa60-6d2165874cae)

Smartphone:

Device 1: Xiaomi Redmi 4 X

Browser 1: Chrome / Brave

Device 2: Xiaomi Redmi Note 10 Lite

Browser 2: Chrome / Brave

**Comment by axtina** [comment]
addressed in #47. closing
